### ISSUE TITLE
build issues on JDK9

### ISSUE THREAD

**Issue by jplock** [smoketurner/dropwizard-money#3]
@cowtowncoder, do you know if there are any open issues related to number parsing when it relates to Locale's that might impact Jackson v2.9.1 (which is used by Dropwizard v1.2.0 - https://github.com/dropwizard/dropwizard/blob/v1.2.0/dropwizard-bom/pom.xml#L27) that are specific to JDK9?

I have a set of tests that pass in openjdk8 but are failing in openjdk9 and I suspect they are Locale related somehow.

https://travis-ci.org/smoketurner/dropwizard-money/jobs/304787859#L796

Thanks for the help.

**Comment by cowtowncoder** [comment]
I am not aware of such issues. I don't use JDK9 myself for builds since integration has proven difficult, but I have done some spot tests (esp. during pre-release versions).
Testing for `Locale` in `jackson-databind` exists, but is not particularly wide. But all those tests did pass with JDK9 last I ran them for what that is worth.
